theme: jekyll-theme-slate
google_verify: QtiCpHJXx6ze17AIVUJso8v0cXoF4LGjsCkYLR6ByIk

navbar-links:
  Resources:
    - MS-KILE 3.1.1.2 Cryptographic Material: "https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-kile/7a7b081d-c0c6-46f4-acbf-a439664270b8"
  Author's home: "http://www.adamburford.com"

social-network-links:
linkedin: adamburford
email: "adam@adamburford.com"

share-links-active:
linkedin: true
