theme: jekyll-theme-slate
google_verify: QtiCpHJXx6ze17AIVUJso8v0cXoF4LGjsCkYLR6ByIk
bing_site_verification: 976CEC2B855BC82AA2D394F7DE5B5A1D

navbar-links:
  Resources:
    - MS-KILE 3.1.1.2 Cryptographic Material: "https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-kile/7a7b081d-c0c6-46f4-acbf-a439664270b8"
  Author's home: "http://www.adamburford.com"

share-links-active:
author:
email: "adam@adamburford.com"

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
#  rss: true
#  email: "someone@example.com"
#  facebook: userid
  github: TheRealAdamBurford
#  twitter: userid
#  reddit: yourname
  linkedin: adamburford
#  xing: yourname
#  snapchat: userid
#  instagram: userid
#  youtube: user/userid
#  spotify: yourname
#  telephone: +11235551212
#  steam: userid
#  twitch: yourname
#  yelp: yourname
