theme: jekyll-theme-slate
google_verify: QtiCpHJXx6ze17AIVUJso8v0cXoF4LGjsCkYLR6ByIk
social-network-links:
email: "adam@adamburford.com"
github: "https://github.com/TheRealAdamBurford"
linkedin: "https://www.linkedin.com/in/adamburford/"
